#!/bin/sh

case "$1" in
  start)
    echo "Starting FBV Splash Screen..."
    fbv -f -s /usr/share/backgrounds/splash.png &
    sleep 2
    cd /opt/streets_of_rogue && ./StreetsOfRogueLinux.x86_64
    ;;
  stop)
    echo "Stopping Splash Screen..."
    killall fbv
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac
exit 0
